export {
  emitBlock,
  blockToDSL,
  stackToDSL,
  generateDSLFromStacks,
  generateDSLFromFlow,
  generateDSL,
  nodeDSL,
  validateFlow,
  renderIr,
  SCHEMA_VERSIONS_FOR_UI,
  inferRequiredFeaturesFromFlow,
  inferRequiredFeaturesFromStacks,
  buildProjectManifestDraft,
  buildProjectManifestDraftFromStacks,
  buildProjectGraphDocumentFromFlow,
  buildProjectGraphDocumentFromStacks,
  buildProjectGraphDocumentFromFlowAsync,
  buildProjectGraphDocumentFromStacksAsync,
  normalizeFlowNode,
  validateProjectIr,
  validateProjectIrStrict,
  assertCompilableFlow,
  IR_BUILD_COMPILE_STRICT,
  IR_BUILD_DEFAULTS,
  irBuildOptionsFromValidateMode,
  migrateFlowToIrV2,
  CompilationError,
  buildProjectIrV2,
  irNodeDslEmitName,
  validateIrV2,
  getCompilerId,
  IR_SCHEMA_VERSION_V1,
  IR_SCHEMA_VERSION_V2,
  IR_SCHEMA_VERSION_DEFAULT,
  IR_NODE_REGISTRY,
} from '../core/dslCodegen.js';

export { buildMinimalProjectManifest } from '../core/manifests/minimalManifest.js';
export {
  buildProjectGraphDocument,
  GRAPH_DOCUMENT_DEPENDENCY_GRAPH_KEY,
  CONTENT_DIGEST_PREFIX,
  GRAPH_DOCUMENT_BLOB_KEYS,
  graphBlobRefKey,
  graphBlobDigestKey,
  normalizeContentDigest,
  contentDigestCanonicalJson,
  verifyContentDigestCanonicalJson,
  casUriFromContentDigest,
  contentDigestFromCasUri,
  graphDocumentToReferenceMode,
  graphDocumentResolveRefs,
  graphDocumentResolveRefsAsync,
  graphDocumentReferencedSections,
  graphDocumentPickBlobs,
  graphDocumentOmitBlobs,
  graphDocumentAttachDigestsAsync,
  graphDocumentVerifyDigestsAsync,
} from '../core/manifests/graphDocumentRefs.js';
export {
  BLOB_MANIFEST_VERSION,
  normalizeBlobManifestEntry,
  normalizeBlobManifest,
  buildBlobManifestFromGraphDocumentAsync,
  blobManifestTotalBytes,
  blobManifestNonEmptySections,
  enrichGraphDocumentWithBlobManifestAsync,
} from '../core/manifests/blobManifest.js';
export {
  CHUNK_KEY_SPEC_VERSION,
  CHUNK_KEY_NAMESPACE,
  CHUNK_KEY_SUGGESTED_HANDLER_ROLES,
  parseChunkKey,
  formatChunkKey,
  isValidChunkKey,
  assertValidChunkKey,
  compareChunkKeysUtf8,
} from '../core/manifests/chunkKeySpec.js';
export {
  CHUNK_DEPENDENCY_GRAPH_SCHEMA_VERSION,
  CHUNK_DEPENDENCY_EDGE_KIND,
  normalizeChunkDependencyEdgeV0,
  normalizeChunkDependencyGraphV0,
} from '../core/manifests/chunkDependencyGraph.js';
export {
  CHUNK_INVALIDATION_PROTOCOL_VERSION,
  dependencyGraphReverseConsumers,
  planSemanticInvalidationV0,
} from '../core/manifests/chunkInvalidation.js';
export {
  CHUNK_MERKLE_TREE_VERSION,
  chunkMerkleLeafHashAsync,
  chunkMerkleNodeHashAsync,
  merkleRootFromSemanticChunksAsync,
  verifySemanticMerkleRootAsync,
} from '../core/manifests/chunkMerkle.js';
export {
  UNIFIED_DIAGNOSTIC_PROTOCOL_VERSION,
  DIAGNOSTIC_PHASE,
  DIAGNOSTIC_CODE,
  normalizeUnifiedDiagnosticV1,
  diagnosticV1FromStructuredSyntax,
  diagnosticV1FromSemanticError,
  diagnosticV1FromSemanticWarning,
  diagnosticV1FromUnsupportedFeatures,
  diagnosticV1FromDryRunBlocked,
  diagnosticV1FromDryRunWarning,
  primaryErrorDiagnosticV1,
  unifiedDiagnosticsV1ToJson,
  VALIDATION_PIPELINE_FINGERPRINT_VERSION,
  SEMANTIC_RULES_VERSION,
  DEFAULT_GRAMMAR_REVISION,
  VALIDATION_ORCHESTRATION_VERSION,
  computeValidationPipelineFingerprintV1,
  VALIDATION_ARTIFACT_MANIFEST_VERSION,
  buildValidationArtifactManifestV1,
  normalizeValidationArtifactManifestV1,
  validationArtifactManifestFromPipelineResult,
  VALIDATION_CACHE_ENTRY_VERSION,
  VALIDATION_CACHE_STATUS,
  buildValidationCacheEntryV1,
  normalizeValidationCacheEntryV1,
  validationCacheArtifactRefFromDigest,
  validationCacheLogicalKeyV1,
  validationCacheEntryV1FromArtifactRef,
  SIGNED_VALIDATION_MANIFEST_PROTOCOL_VERSION,
  VALIDATION_SIGNATURE_ALGORITHM,
  validationArtifactSigningPayloadV1,
  buildSignedValidationManifestV1,
  normalizeSignedValidationManifestV1,
} from '../core/diagnostics/index.js';
export {
  PROJECT_MANIFEST_FORMAT_VERSION,
  PROJECT_GRAPH_DOCUMENT_SCHEMA_VERSION,
  PROJECT_GRAPH_DOCUMENT_TYPE,
} from '../core/manifests/constants.js';
